site_name: Finance Models
theme:
  name: bootstrap
repo_url: https://github.com/TheStatsProject/PP1A
nav:
  - Home: index.md
  - Articles:
      - New Article: new-article.md
      - About: about.md
  - Guides:
      - Getting Started: getting-started.md
      - Advanced Topics: advanced-topics.md
  - Resources:
      - FAQs: faqs.md
      - API Reference: api-reference.md
